server {
    server_name temnaarea.site www.temnaarea.site;

    root /var/www/temnaarea-site;
    index index.html;

    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / {
        try_files $uri $uri/ /index.html;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/temnaarea.site/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/temnaarea.site/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = www.temnaarea.site) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = temnaarea.site) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name temnaarea.site www.temnaarea.site;
    return 404; # managed by Certbot
}
